apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
spec:
  destination:
    name: ''
    namespace: flask
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests
    repoURL: 'https://github.com/IsaacAM50/devops11-final-manifest'
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
