apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
        - name: blackbox-exporter
          image: prom/blackbox-exporter:v0.24.0
          args:
            - "--config.file=/etc/blackbox_exporter/blackbox.yml"
          ports:
            - containerPort: 9115
              name: http
          volumeMounts:
            - name: config
              mountPath: /etc/blackbox_exporter
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "64Mi"
              cpu: "50m"
      volumes:
        - name: config
          configMap:
            name: blackbox-exporter-config