apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: flask
  labels:
    app: blackbox-exporter
spec:
  selector:
    app: blackbox-exporter
  ports:
    - port: 9115
      targetPort: 9115
  type: ClusterIP