apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5000"
    spec:
      containers:
        - name: flask
          image: ghcr.io/juarru/devops11a-project-app:main
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: http
            - containerPort: 5000
              name: metrics
          env:
            - name: ELASTICSEARCH_HOST
              value: elasticsearch.flask.svc.cluster.local
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: ENABLE_METRICS
              value: "true"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5