resources:
  - app/app-deployment.yaml
  - app/app-svc.yaml
  - redis/redis-deployment.yaml
  - redis/redis-svc.yaml
  - elastic/elastic-deployment.yaml
  - elastic/elastic-svc.yaml
  - namespace.yaml
