apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: flask-app-monitoring
  namespace: flask
spec:
  selector:
    matchLabels:
      app: flask
  endpoints:
  - port: metrics
    interval: 30s
    path: "/metrics"
    metricRelabeling:
    - action: keep
      sourceLabels: [__name__]
      regex: 'server_requests_total|healthcheck_requests_total|main_requests_total|logs_requests_total'