---
apiVersion: v1
kind: Service
metadata:
  name: flask-metricas
  namespace: flask
  labels:
    app: flask
    service: metrics
spec:
  selector:
    app: flask
  ports:
  - port: 5000
    targetPort: metrics
    name: metrics
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-metricas
  namespace: flask
  labels:
    app: redis
    service: metrics
spec:
  selector:
    app: redis
  ports:
  - port: 9121
    targetPort: metrics
    name: metrics
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-metricas
  namespace: flask
  labels:
    app: elasticsearch
    service: metrics
spec:
  selector:
    app: elasticsearch
  ports:
  - port: 9114
    targetPort: metrics
    name: metrics
  type: ClusterIP