# Servicio para exponer las métricas
apiVersion: v1
kind: Service
metadata:
  name: flask-metrics
  namespace: flask
  labels:
    app: flask
    service: metrics
spec:
  selector:
    app: flask
  ports:
  - port: 9090
    targetPort: metrics
    name: metrics
  type: ClusterIP