apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: flask
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
  - port: 80
    targetPort: 3000
    name: web
  type: ClusterIP