apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: flask
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus.flask.svc.cluster.local:9090
      version: 1
      editable: true
      isDefault: true