{
 "title": "Flask Endpoints Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Endpoint Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"flask-health-endpoint\"}",
     "legendFormat": "Health Endpoint"
    },
    {
     "expr": "probe_success{job=\"flask-logs-endpoint\"}",
     "legendFormat": "Logs Endpoint"
    },
    {
     "expr": "probe_success{job=\"flask-main-endpoint\"}",
     "legendFormat": "Main Endpoint"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"flask-health-endpoint\"}",
     "legendFormat": "Health Endpoint"
    },
    {
     "expr": "probe_duration_seconds{job=\"flask-logs-endpoint\"}",
     "legendFormat": "Logs Endpoint"
    },
    {
     "expr": "probe_duration_seconds{job=\"flask-main-endpoint\"}",
     "legendFormat": "Main Endpoint"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"flask-health-endpoint\"}",
     "legendFormat": "Health Endpoint"
    },
    {
     "expr": "probe_http_status_code{job=\"flask-logs-endpoint\"}",
     "legendFormat": "Logs Endpoint"
    },
    {
     "expr": "probe_http_status_code{job=\"flask-main-endpoint\"}",
     "legendFormat": "Main Endpoint"
    }
   ]
  }
 ]
}